name: Feature Request Issues
description: Use this template for raising a feature request. If this doesn’t look right, choose a different type.
labels: 'type/feature'
body:
  - type: markdown
    id: linkmodel
    attributes:
      value: Please make sure that this is a feature request.
  - type: textarea
    id: behaviour
    attributes:
      label: Describe the feature and the current behaviour/state
      render: shell
    validations:
      required: true
